/**
 * Copyright © 2013/2014, Veljko Zivkovic
 * All rights reserved.
 *
 * No portion of this file may be reproduced in any form, or by any means, without the prior written
 * consent of the author.
 */
package com.tirion.db.store.builder.stats.analyzer.range;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import com.tirion.common.sequence.array.Array;
import com.tirion.common.type.Type;
import com.tirion.db.store.builder.stats.model.range.Comparators;
import com.tirion.db.store.builder.stats.model.range.DoubleRange;
import com.tirion.db.store.builder.stats.model.range.Range;
import com.tirion.db.store.builder.stats.model.range.Ranges;

/**
 * This class was autogenerated. Do not edit manually.
 */
public final class DoubleRangeAnalyzer extends AbstractRangeAnalyzer {

	public DoubleRangeAnalyzer(RangesConf conf) {
		super(conf);
	}

	@Override
	public Ranges analyze(Array array) {
		List<DoubleRange> ranges = new ArrayList<DoubleRange>();
		double[] input = cloneAndSortArray((double[])array.getUnderlying());
		int index = 1;
		while(true) {
			if(index == input.length) {
				break;
			}
			double start = input[index - 1];
			double end = input[index];
			if(shouldIncludeSkipRange(start, end)) {
				ranges.add(new DoubleRange(start, end));
			}
			++index;
		}
		if(ranges.isEmpty()) {
			return null;
		}
		Ranges result = new Ranges(Type.DOUBLE);
		for(Range range : tuneSkipRanges(ranges)) {
			result.append(range);
		}
		return result;
	}
	
	private List<DoubleRange> tuneSkipRanges(List<DoubleRange> ranges) {
		if(ranges.size() <= getMaxSkipRangesPerPage()) {
			return ranges;
		}
		Collections.sort(ranges, new Comparators.DoubleRangeComparator());
		int count = Math.min(getMaxSkipRangesPerPage(), ranges.size());
		List<DoubleRange> result = new ArrayList<DoubleRange>();
		for (int i = ranges.size() - 1; i >= ranges.size() - count; i--) {
			result.add(ranges.get(i));
		}
		return result;
	}
	
	private boolean shouldIncludeSkipRange(double start, double end) {
		return (end - start - 1) >= 
					getSkipRangeRealThreshold();
			}
	
	private double[] cloneAndSortArray(double[] input) {
		double[] clone = new double[input.length];
		System.arraycopy(input, 0, clone, 0, input.length);
		Arrays.sort(clone);
		return clone;
	}
}
