/**
 * Copyright © 2013/2014, Veljko Zivkovic
 * All rights reserved.
 *
 * No portion of this file may be reproduced in any form, or by any means, without the prior written
 * consent of the author.
 */
package com.tirion.db.store.builder.stats.analyzer.range;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import com.tirion.common.sequence.array.Array;
import com.tirion.common.type.Type;
import com.tirion.db.store.builder.stats.model.range.Comparators;
import com.tirion.db.store.builder.stats.model.range.FloatRange;
import com.tirion.db.store.builder.stats.model.range.Range;
import com.tirion.db.store.builder.stats.model.range.Ranges;

/**
 * This class was autogenerated. Do not edit manually.
 */
public final class FloatRangeAnalyzer extends AbstractRangeAnalyzer {

	public FloatRangeAnalyzer(RangesConf conf) {
		super(conf);
	}

	@Override
	public Ranges analyze(Array array) {
		List<FloatRange> ranges = new ArrayList<FloatRange>();
		float[] input = cloneAndSortArray((float[])array.getUnderlying());
		int index = 1;
		while(true) {
			if(index == input.length) {
				break;
			}
			float start = input[index - 1];
			float end = input[index];
			if(shouldIncludeSkipRange(start, end)) {
				ranges.add(new FloatRange(start, end));
			}
			++index;
		}
		if(ranges.isEmpty()) {
			return null;
		}
		Ranges result = new Ranges(Type.FLOAT);
		for(Range range : tuneSkipRanges(ranges)) {
			result.append(range);
		}
		return result;
	}
	
	private List<FloatRange> tuneSkipRanges(List<FloatRange> ranges) {
		if(ranges.size() <= getMaxSkipRangesPerPage()) {
			return ranges;
		}
		Collections.sort(ranges, new Comparators.FloatRangeComparator());
		int count = Math.min(getMaxSkipRangesPerPage(), ranges.size());
		List<FloatRange> result = new ArrayList<FloatRange>();
		for (int i = ranges.size() - 1; i >= ranges.size() - count; i--) {
			result.add(ranges.get(i));
		}
		return result;
	}
	
	private boolean shouldIncludeSkipRange(float start, float end) {
		return (end - start - 1) >= 
					getSkipRangeRealThreshold();
			}
	
	private float[] cloneAndSortArray(float[] input) {
		float[] clone = new float[input.length];
		System.arraycopy(input, 0, clone, 0, input.length);
		Arrays.sort(clone);
		return clone;
	}
}
