/**
 * Copyright © 2013/2014, Veljko Zivkovic
 * All rights reserved.
 *
 * No portion of this file may be reproduced in any form, or by any means, without the prior written
 * consent of the author.
 */
package com.tirion.db.store.builder.stats.analyzer.range;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import com.tirion.common.sequence.array.Array;
import com.tirion.common.type.Type;
import com.tirion.db.store.builder.stats.model.range.Comparators;
import com.tirion.db.store.builder.stats.model.range.ShortRange;
import com.tirion.db.store.builder.stats.model.range.Range;
import com.tirion.db.store.builder.stats.model.range.Ranges;

/**
 * This class was autogenerated. Do not edit manually.
 */
public final class ShortRangeAnalyzer extends AbstractRangeAnalyzer {

	public ShortRangeAnalyzer(RangesConf conf) {
		super(conf);
	}

	@Override
	public Ranges analyze(Array array) {
		List<ShortRange> ranges = new ArrayList<ShortRange>();
		short[] input = cloneAndSortArray((short[])array.getUnderlying());
		int index = 1;
		while(true) {
			if(index == input.length) {
				break;
			}
			short start = input[index - 1];
			short end = input[index];
			if(shouldIncludeSkipRange(start, end)) {
				ranges.add(new ShortRange(start, end));
			}
			++index;
		}
		if(ranges.isEmpty()) {
			return null;
		}
		Ranges result = new Ranges(Type.SHORT);
		for(Range range : tuneSkipRanges(ranges)) {
			result.append(range);
		}
		return result;
	}
	
	private List<ShortRange> tuneSkipRanges(List<ShortRange> ranges) {
		if(ranges.size() <= getMaxSkipRangesPerPage()) {
			return ranges;
		}
		Collections.sort(ranges, new Comparators.ShortRangeComparator());
		int count = Math.min(getMaxSkipRangesPerPage(), ranges.size());
		List<ShortRange> result = new ArrayList<ShortRange>();
		for (int i = ranges.size() - 1; i >= ranges.size() - count; i--) {
			result.add(ranges.get(i));
		}
		return result;
	}
	
	private boolean shouldIncludeSkipRange(short start, short end) {
		return (end - start - 1) >= 
					getSkipRangeDiscreteThreshold();
			}
	
	private short[] cloneAndSortArray(short[] input) {
		short[] clone = new short[input.length];
		System.arraycopy(input, 0, clone, 0, input.length);
		Arrays.sort(clone);
		return clone;
	}
}
