/**
 * Copyright © 2013/2014, Veljko Zivkovic
 * All rights reserved.
 *
 * No portion of this file may be reproduced in any form, or by any means, without the prior written
 * consent of the author.
 */
package com.tirion.db.sql.exec.operator.physical.scan.filter.array;

import java.util.Set;

import com.tirion.db.sql.exec.operator.physical.scan.rowid.sink.RowIdSink;

/**
 * This class was autogenerated. Do not edit manually.
 * 
 * @author Veljko Zivkovic, Copyright (C) All Rights Reserved
 */
public abstract class DoubleArrayFilter extends AbstractArrayFilter {

	protected final double[] array;
	
	public DoubleArrayFilter(RowIdSink rowIdSink, long startRowId, double[] array) {
		super(rowIdSink, startRowId);
		this.array = array;
	}
	
	public static final class DoubleBetweenArrayFilter extends DoubleArrayFilter {

		private final double low;
		private final double high;
		
		public DoubleBetweenArrayFilter(RowIdSink rowIdSink, long startRowId, double[] array, double low, double high) {
			super(rowIdSink, startRowId, array);
			this.low = low;
			this.high = high;
		}

		@Override
		public void apply() {
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(low <= array[i] && array[i] <= high) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static final class DoubleInArrayFilter extends DoubleArrayFilter {

		private final Set<Double> set;

		public DoubleInArrayFilter(RowIdSink rowIdSink, long startRowId, double[] array, Set<Double> set) {
			super(rowIdSink, startRowId, array);
			this.set = set;
		}

		@Override
		public void apply() {	
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(set.contains(array[i])) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static abstract class SimpleDoubleArrayFilter extends DoubleArrayFilter {
		
		protected final double value;

		public SimpleDoubleArrayFilter(RowIdSink rowIdSink, long startRowId, double[] array, double value) {
			super(rowIdSink, startRowId, array);
			this.value = value;
		}
	}
	
	public static final class DoubleEqArrayFilter extends SimpleDoubleArrayFilter {

		public DoubleEqArrayFilter(RowIdSink rowIdSink, long startRowId, double[] array, double value) {
			super(rowIdSink, startRowId, array, value);
		}

		@Override
		public void apply() {
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(array[i] == value) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static final class DoubleNeqArrayFilter extends SimpleDoubleArrayFilter {

		public DoubleNeqArrayFilter(RowIdSink rowIdSink, long startRowId, double[] array, double value) {
			super(rowIdSink, startRowId, array, value);
		}

		@Override
		public void apply() {
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(array[i] != value) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static final class DoubleLtArrayFilter extends SimpleDoubleArrayFilter {

		public DoubleLtArrayFilter(RowIdSink rowIdSink, long startRowId, double[] array, double value) {
			super(rowIdSink, startRowId, array, value);
		}

		@Override
		public void apply() {
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(array[i] < value) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static final class DoubleLtEqArrayFilter extends SimpleDoubleArrayFilter {

		public DoubleLtEqArrayFilter(RowIdSink rowIdSink, long startRowId, double[] array, double value) {
			super(rowIdSink, startRowId, array, value);
		}

		@Override
		public void apply() {
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(array[i] <= value) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static final class DoubleGtArrayFilter extends SimpleDoubleArrayFilter {

		public DoubleGtArrayFilter(RowIdSink rowIdSink, long startRowId, double[] array, double value) {
			super(rowIdSink, startRowId, array, value);
		}

		@Override
		public void apply() {			
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(array[i] > value) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static final class DoubleGtEqArrayFilter extends SimpleDoubleArrayFilter {

		public DoubleGtEqArrayFilter(RowIdSink rowIdSink, long startRowId, double[] array, double value) {
			super(rowIdSink, startRowId, array, value);
		}

		@Override
		public void apply() {
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(array[i] >= value) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
}
