/**
 * Copyright © 2013/2014, Veljko Zivkovic
 * All rights reserved.
 *
 * No portion of this file may be reproduced in any form, or by any means, without the prior written
 * consent of the author.
 */
package com.tirion.db.sql.exec.operator.physical.scan.filter.array;

import java.util.Set;

import com.tirion.db.sql.exec.operator.physical.scan.rowid.sink.RowIdSink;

/**
 * This class was autogenerated. Do not edit manually.
 * 
 * @author Veljko Zivkovic, Copyright (C) All Rights Reserved
 */
public abstract class LongArrayFilter extends AbstractArrayFilter {

	protected final long[] array;
	
	public LongArrayFilter(RowIdSink rowIdSink, long startRowId, long[] array) {
		super(rowIdSink, startRowId);
		this.array = array;
	}
	
	public static final class LongBetweenArrayFilter extends LongArrayFilter {

		private final long low;
		private final long high;
		
		public LongBetweenArrayFilter(RowIdSink rowIdSink, long startRowId, long[] array, long low, long high) {
			super(rowIdSink, startRowId, array);
			this.low = low;
			this.high = high;
		}

		@Override
		public void apply() {
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(low <= array[i] && array[i] <= high) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static final class LongInArrayFilter extends LongArrayFilter {

		private final Set<Long> set;

		public LongInArrayFilter(RowIdSink rowIdSink, long startRowId, long[] array, Set<Long> set) {
			super(rowIdSink, startRowId, array);
			this.set = set;
		}

		@Override
		public void apply() {	
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(set.contains(array[i])) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static abstract class SimpleLongArrayFilter extends LongArrayFilter {
		
		protected final long value;

		public SimpleLongArrayFilter(RowIdSink rowIdSink, long startRowId, long[] array, long value) {
			super(rowIdSink, startRowId, array);
			this.value = value;
		}
	}
	
	public static final class LongEqArrayFilter extends SimpleLongArrayFilter {

		public LongEqArrayFilter(RowIdSink rowIdSink, long startRowId, long[] array, long value) {
			super(rowIdSink, startRowId, array, value);
		}

		@Override
		public void apply() {
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(array[i] == value) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static final class LongNeqArrayFilter extends SimpleLongArrayFilter {

		public LongNeqArrayFilter(RowIdSink rowIdSink, long startRowId, long[] array, long value) {
			super(rowIdSink, startRowId, array, value);
		}

		@Override
		public void apply() {
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(array[i] != value) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static final class LongLtArrayFilter extends SimpleLongArrayFilter {

		public LongLtArrayFilter(RowIdSink rowIdSink, long startRowId, long[] array, long value) {
			super(rowIdSink, startRowId, array, value);
		}

		@Override
		public void apply() {
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(array[i] < value) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static final class LongLtEqArrayFilter extends SimpleLongArrayFilter {

		public LongLtEqArrayFilter(RowIdSink rowIdSink, long startRowId, long[] array, long value) {
			super(rowIdSink, startRowId, array, value);
		}

		@Override
		public void apply() {
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(array[i] <= value) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static final class LongGtArrayFilter extends SimpleLongArrayFilter {

		public LongGtArrayFilter(RowIdSink rowIdSink, long startRowId, long[] array, long value) {
			super(rowIdSink, startRowId, array, value);
		}

		@Override
		public void apply() {			
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(array[i] > value) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
	
	public static final class LongGtEqArrayFilter extends SimpleLongArrayFilter {

		public LongGtEqArrayFilter(RowIdSink rowIdSink, long startRowId, long[] array, long value) {
			super(rowIdSink, startRowId, array, value);
		}

		@Override
		public void apply() {
			long rowId = getStartRowId();
			for (int i = 0; i < array.length; i++) {
				if(array[i] >= value) {
					getRowIdSink().onRowId(rowId);
				}
				++rowId;
			}
		}
	}
}
