/**
 * Copyright © 2013/2014, Veljko Zivkovic
 * All rights reserved.
 *
 * No portion of this file may be reproduced in any form, or by any means, without the prior written
 * consent of the author.
 */
package com.tirion.db.sql.exec.operator.physical.scan.filter.buffer;

import java.nio.ByteBuffer;
import java.util.Set;

import com.tirion.common.type.Type;
import com.tirion.db.sql.exec.operator.physical.scan.rowid.sink.RowIdSink;

/**
 * This class was autogenerated. Do not edit manually.
 * 
 * @author Veljko Zivkovic
 */
public abstract class IntegerBufferFilter extends AbstractBufferFilter {

	public IntegerBufferFilter(RowIdSink rowIdSink, long startRowId, int startPosition, int count, ByteBuffer buffer) {
		super(rowIdSink, startRowId, startPosition, count, buffer);
	}

	public static final class IntegerBetweenBufferFilter extends IntegerBufferFilter {

		private final int low;
		private final int high;
		
		public IntegerBetweenBufferFilter(RowIdSink rowIdSink, long startRowId, int startPosition, int count, ByteBuffer buffer, int low, int high) {
			super(rowIdSink, startRowId, startPosition, count, buffer);
			this.low = low;
			this.high = high;
		}

		@Override
		public void apply() {	
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							final int value = buffer.getInt(position);
							if(low <= value && value <= high) {
					rowIdSink.onRowId(rowId);
				}
				position += Type.INT.getWidth();
				++rowId;
			}
		}
	}
	
	public static final class IntegerInBufferFilter extends IntegerBufferFilter {

		private final Set<Integer> set;

		public IntegerInBufferFilter(RowIdSink rowIdSink, long startRowId, int startPosition, int count, ByteBuffer buffer, Set<Integer> set) {
			super(rowIdSink, startRowId, startPosition, count, buffer);
			this.set = set;
		}

		@Override
		public void apply() {	
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							final int value = buffer.getInt(position);
							if(set.contains(value)) {
					rowIdSink.onRowId(rowId);
				}
				position += Type.INT.getWidth();
				++rowId;
			}
		}
	}
	
	public static abstract class SimpleIntegerBufferFilter extends IntegerBufferFilter {
		
		protected final int value;

		public SimpleIntegerBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, int value) {
			super(rowIdSink, startRowId, position, count, buffer);
			this.value = value;
		}
	}
	
	public static final class IntegerEqBufferFilter extends SimpleIntegerBufferFilter {

		public IntegerEqBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, int value) {
			super(rowIdSink, startRowId, position, count, buffer, value);
		}

		@Override
		public void apply() {
			long rowId = startRowId;
			int position = startPosition;
			for (int i = 0; i < count; i++) {
							if(buffer.getInt(position) == value) {
								rowIdSink.onRowId(rowId);
				}
				position += Type.INT.getWidth();
				++rowId;
			}
		}
	}
	
	public static final class IntegerNeqBufferFilter extends SimpleIntegerBufferFilter {

		public IntegerNeqBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, int value) {
			super(rowIdSink, startRowId, position, count, buffer, value);
		}

		@Override
		public void apply() {
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							if(buffer.getInt(position) != value) {
								rowIdSink.onRowId(rowId);
				}
				position += Type.INT.getWidth();
				++rowId;
			}
		}
	}
	
	public static final class IntegerLtBufferFilter extends SimpleIntegerBufferFilter {

		public IntegerLtBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, int value) {
			super(rowIdSink, startRowId, position, count, buffer, value);
		}

		@Override
		public void apply() {
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							if(buffer.getInt(position) < value) {
								rowIdSink.onRowId(rowId);
				}
				position += Type.INT.getWidth();
				++rowId;
			}
		}
	}
	
	public static final class IntegerLtEqBufferFilter extends SimpleIntegerBufferFilter {

		public IntegerLtEqBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, int value) {
			super(rowIdSink, startRowId, position, count, buffer, value);
		}

		@Override
		public void apply() {
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							if(buffer.getInt(position) <= value) {
								rowIdSink.onRowId(rowId);
				}
				position += Type.INT.getWidth();
				++rowId;
			}
		}
	}
	
	public static final class IntegerGtBufferFilter extends SimpleIntegerBufferFilter {

		public IntegerGtBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, int value) {
			super(rowIdSink, startRowId, position, count, buffer, value);
		}

		@Override
		public void apply() {
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							if(buffer.getInt(position) > value) {
								rowIdSink.onRowId(rowId);
				}
				position += Type.INT.getWidth();
				++rowId;
			}
		}
	}
	
	public static final class IntegerGtEqBufferFilter extends SimpleIntegerBufferFilter {

		public IntegerGtEqBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, int value) {
			super(rowIdSink, startRowId, position, count, buffer, value);
		}

		@Override
		public void apply() {
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							if(buffer.getInt(position) >= value) {
								rowIdSink.onRowId(rowId);
				}
				position += Type.INT.getWidth();
				++rowId;
			}
		}
	}
}