/**
 * Copyright © 2013/2014, Veljko Zivkovic
 * All rights reserved.
 *
 * No portion of this file may be reproduced in any form, or by any means, without the prior written
 * consent of the author.
 */
package com.tirion.db.sql.exec.operator.physical.scan.filter.buffer;

import java.nio.ByteBuffer;
import java.util.Set;

import com.tirion.common.type.Type;
import com.tirion.db.sql.exec.operator.physical.scan.rowid.sink.RowIdSink;

/**
 * This class was autogenerated. Do not edit manually.
 * 
 * @author Veljko Zivkovic
 */
public abstract class LongBufferFilter extends AbstractBufferFilter {

	public LongBufferFilter(RowIdSink rowIdSink, long startRowId, int startPosition, int count, ByteBuffer buffer) {
		super(rowIdSink, startRowId, startPosition, count, buffer);
	}

	public static final class LongBetweenBufferFilter extends LongBufferFilter {

		private final long low;
		private final long high;
		
		public LongBetweenBufferFilter(RowIdSink rowIdSink, long startRowId, int startPosition, int count, ByteBuffer buffer, long low, long high) {
			super(rowIdSink, startRowId, startPosition, count, buffer);
			this.low = low;
			this.high = high;
		}

		@Override
		public void apply() {	
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							final long value = buffer.getLong(position);
							if(low <= value && value <= high) {
					rowIdSink.onRowId(rowId);
				}
				position += Type.LONG.getWidth();
				++rowId;
			}
		}
	}
	
	public static final class LongInBufferFilter extends LongBufferFilter {

		private final Set<Long> set;

		public LongInBufferFilter(RowIdSink rowIdSink, long startRowId, int startPosition, int count, ByteBuffer buffer, Set<Long> set) {
			super(rowIdSink, startRowId, startPosition, count, buffer);
			this.set = set;
		}

		@Override
		public void apply() {	
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							final long value = buffer.getLong(position);
							if(set.contains(value)) {
					rowIdSink.onRowId(rowId);
				}
				position += Type.LONG.getWidth();
				++rowId;
			}
		}
	}
	
	public static abstract class SimpleLongBufferFilter extends LongBufferFilter {
		
		protected final long value;

		public SimpleLongBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, long value) {
			super(rowIdSink, startRowId, position, count, buffer);
			this.value = value;
		}
	}
	
	public static final class LongEqBufferFilter extends SimpleLongBufferFilter {

		public LongEqBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, long value) {
			super(rowIdSink, startRowId, position, count, buffer, value);
		}

		@Override
		public void apply() {
			long rowId = startRowId;
			int position = startPosition;
			for (int i = 0; i < count; i++) {
							if(buffer.getLong(position) == value) {
								rowIdSink.onRowId(rowId);
				}
				position += Type.LONG.getWidth();
				++rowId;
			}
		}
	}
	
	public static final class LongNeqBufferFilter extends SimpleLongBufferFilter {

		public LongNeqBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, long value) {
			super(rowIdSink, startRowId, position, count, buffer, value);
		}

		@Override
		public void apply() {
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							if(buffer.getLong(position) != value) {
								rowIdSink.onRowId(rowId);
				}
				position += Type.LONG.getWidth();
				++rowId;
			}
		}
	}
	
	public static final class LongLtBufferFilter extends SimpleLongBufferFilter {

		public LongLtBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, long value) {
			super(rowIdSink, startRowId, position, count, buffer, value);
		}

		@Override
		public void apply() {
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							if(buffer.getLong(position) < value) {
								rowIdSink.onRowId(rowId);
				}
				position += Type.LONG.getWidth();
				++rowId;
			}
		}
	}
	
	public static final class LongLtEqBufferFilter extends SimpleLongBufferFilter {

		public LongLtEqBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, long value) {
			super(rowIdSink, startRowId, position, count, buffer, value);
		}

		@Override
		public void apply() {
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							if(buffer.getLong(position) <= value) {
								rowIdSink.onRowId(rowId);
				}
				position += Type.LONG.getWidth();
				++rowId;
			}
		}
	}
	
	public static final class LongGtBufferFilter extends SimpleLongBufferFilter {

		public LongGtBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, long value) {
			super(rowIdSink, startRowId, position, count, buffer, value);
		}

		@Override
		public void apply() {
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							if(buffer.getLong(position) > value) {
								rowIdSink.onRowId(rowId);
				}
				position += Type.LONG.getWidth();
				++rowId;
			}
		}
	}
	
	public static final class LongGtEqBufferFilter extends SimpleLongBufferFilter {

		public LongGtEqBufferFilter(RowIdSink rowIdSink, long startRowId, int position, int count, ByteBuffer buffer, long value) {
			super(rowIdSink, startRowId, position, count, buffer, value);
		}

		@Override
		public void apply() {
			int position = startPosition;
			long rowId = startRowId;
			for (int i = 0; i < count; i++) {
							if(buffer.getLong(position) >= value) {
								rowIdSink.onRowId(rowId);
				}
				position += Type.LONG.getWidth();
				++rowId;
			}
		}
	}
}