/**
 * Copyright © 2013/2014, Veljko Zivkovic
 * All rights reserved.
 *
 * No portion of this file may be reproduced in any form, or by any means, without the prior written
 * consent of the author.
 */
package com.tirion.db.store.builder.indexer;
//package com.tirion.db.store.loader.indexer;
//
//import java.util.HashMap;
//import java.util.Map;
//
//import com.tirion.common.array.Array;
//import com.tirion.common.array.Arrays;
//import com.tirion.db.store.bitmap.Bitmap;
//import com.tirion.db.store.bitmap.Bitmaps;
//import com.tirion.db.store.bitmap.CompressedBitmap;
//
///**
// * This class was autogenerated. Do not edit manually.
// * 
// * @author Veljko Zivkovic, Copyright (C) All Rights Reserved
// */
//public final class StringBmIndexer implements BmIndexer<String> {
//
//	@Override
//	public Map<String, Bitmap> build(Array array) {
//		Map<String, Bitmap> map = new HashMap<String, Bitmap>();
//		String[] arr = (String[]) array.getUnderlying();
//		for (int i = 0; i < arr.length; i++) {
//			Bitmap bitmap = map.get(arr[i]);
//			if(bitmap == null) {
//				bitmap = new CompressedBitmap();
//				map.put(arr[i], bitmap);
//			}
//			bitmap.set(i);
//		}
//		return map;
//	}
//
//	@Override
//	public Map<String, Bitmaps> build(Arrays arrays) {
//		Map<String, Bitmaps> map = new HashMap<String, Bitmaps>();
//		for (int i = 0; i < arrays.getCount(); i++) {
//			String[] arr = (String[]) arrays.get(i).getUnderlying();			
//			for (int j = 0; j < arr.length; j++) {
//				Bitmaps bitmaps = map.get(arr[j]);				
//				if(bitmaps == null) {
//					bitmaps = new Bitmaps();
//					map.put(arr[j], bitmaps);
//				}
//				fillWillNulls(bitmaps, i-1);
//				if(!bitmaps.has(i)) {
//					bitmaps.append(new CompressedBitmap());					
//				}
//				bitmaps.get(i).set(j);
//			}
//		}
//		return map;
//	}
//	
//	private void fillWillNulls(Bitmaps bitmaps, int index) {
//		while(!bitmaps.has(index)) {
//			bitmaps.append((Bitmap)null);
//		}
//	}
//}
//
//
//
