/**
 * Copyright © 2013/2014, Veljko Zivkovic
 * All rights reserved.
 *
 * No portion of this file may be reproduced in any form, or by any means, without the prior written
 * consent of the author.
 */
package com.tirion.db.store.builder.stats.analyzer.minmax;

import com.tirion.common.bitmap.Bitmap;
import com.tirion.common.sequence.array.Array;
import com.tirion.db.store.builder.stats.model.minmax.LongMinMax;
import com.tirion.db.store.builder.stats.model.minmax.MinMax;

/**
 * This class was autogenerated. Do not edit manually.
 */
public final class LongMinMaxAnalyzer implements MinMaxAnalyzer {

	@Override
	public MinMax analyze(Array array) {
		long[] input = (long[]) array.getUnderlying();
		Bitmap nullBitmap = array.getNullBitmap();
		if(nullBitmap != null) {
			return analyzeNulls(input, nullBitmap);
		} else {
			return analyzeNoNulls(input);
		}
	}
	
	private MinMax analyzeNulls(long[] input, Bitmap nullBitmap) {
		long min = Long.MAX_VALUE;
		long max = Long.MIN_VALUE;
		for (int i = 0; i < input.length; i++) {
			if(nullBitmap.isSet(i)) {					
				continue;
			}
			final long value = input[i];			
			min = 				   Math.min(value, min);
			max = 				   Math.max(value, max);
		}
		return new LongMinMax(min, max);
	}
	
	private MinMax analyzeNoNulls(long[] input) {
		long min = Long.MAX_VALUE;
		long max = Long.MIN_VALUE;
		for (int i = 0; i < input.length; i++) {
			final long value = input[i];			
			min = 				   Math.min(value, min);
			max = 				   Math.max(value, max);
		}
		return new LongMinMax(min, max);
	}
}
