/**
 * Copyright © 2013/2014, Veljko Zivkovic
 * All rights reserved.
 *
 * No portion of this file may be reproduced in any form, or by any means, without the prior written
 * consent of the author.
 */
package com.tirion.db.store.builder.stats.analyzer.minmax;

import com.tirion.common.bitmap.Bitmap;
import com.tirion.common.sequence.array.Array;
import com.tirion.db.store.builder.stats.model.minmax.ShortMinMax;
import com.tirion.db.store.builder.stats.model.minmax.MinMax;

/**
 * This class was autogenerated. Do not edit manually.
 */
public final class ShortMinMaxAnalyzer implements MinMaxAnalyzer {

	@Override
	public MinMax analyze(Array array) {
		short[] input = (short[]) array.getUnderlying();
		Bitmap nullBitmap = array.getNullBitmap();
		if(nullBitmap != null) {
			return analyzeNulls(input, nullBitmap);
		} else {
			return analyzeNoNulls(input);
		}
	}
	
	private MinMax analyzeNulls(short[] input, Bitmap nullBitmap) {
		short min = Short.MAX_VALUE;
		short max = Short.MIN_VALUE;
		for (int i = 0; i < input.length; i++) {
			if(nullBitmap.isSet(i)) {					
				continue;
			}
			final short value = input[i];			
			min = 				   (short)  Math.min(value, min);
			max = 				   (short)  Math.max(value, max);
		}
		return new ShortMinMax(min, max);
	}
	
	private MinMax analyzeNoNulls(short[] input) {
		short min = Short.MAX_VALUE;
		short max = Short.MIN_VALUE;
		for (int i = 0; i < input.length; i++) {
			final short value = input[i];			
			min = 				   (short)  Math.min(value, min);
			max = 				   (short)  Math.max(value, max);
		}
		return new ShortMinMax(min, max);
	}
}
